/*
 * This file is generated by jOOQ.
*/
package ORM;


import ORM.tables.Article;
import ORM.tables.Attachment;
import ORM.tables.Comment;
import ORM.tables.FollowRelation;
import ORM.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>mallard_dev</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ARTICLE_ARTICLE_USER_ID_FK = Indexes0.ARTICLE_ARTICLE_USER_ID_FK;
    public static final Index ARTICLE_PRIMARY = Indexes0.ARTICLE_PRIMARY;
    public static final Index ATTACHMENT_ATTACHMENT_COMMENT_ID_FK = Indexes0.ATTACHMENT_ATTACHMENT_COMMENT_ID_FK;
    public static final Index ATTACHMENT_PRIMARY = Indexes0.ATTACHMENT_PRIMARY;
    public static final Index COMMENT_COMMENT_ARTICLE_ID_FK = Indexes0.COMMENT_COMMENT_ARTICLE_ID_FK;
    public static final Index COMMENT_COMMENT_COMMENT_ID_FK = Indexes0.COMMENT_COMMENT_COMMENT_ID_FK;
    public static final Index COMMENT_COMMENT_USER_ID_FK = Indexes0.COMMENT_COMMENT_USER_ID_FK;
    public static final Index COMMENT_PRIMARY = Indexes0.COMMENT_PRIMARY;
    public static final Index FOLLOW_RELATION_FOLLOW_RELATION_FOLLOWED_ID_FK = Indexes0.FOLLOW_RELATION_FOLLOW_RELATION_FOLLOWED_ID_FK;
    public static final Index FOLLOW_RELATION_FOLLOW_RELATION_FOLLOWING_ID_FK = Indexes0.FOLLOW_RELATION_FOLLOW_RELATION_FOLLOWING_ID_FK;
    public static final Index FOLLOW_RELATION_PRIMARY = Indexes0.FOLLOW_RELATION_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_USER_EMAIL_UINDEX = Indexes0.USER_USER_EMAIL_UINDEX;
    public static final Index USER_USER_USER_NAME_UINDEX = Indexes0.USER_USER_USER_NAME_UINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index ARTICLE_ARTICLE_USER_ID_FK = createIndex("article_user_id_fk", Article.ARTICLE, new OrderField[] { Article.ARTICLE.AUTHOR }, false);
        public static Index ARTICLE_PRIMARY = createIndex("PRIMARY", Article.ARTICLE, new OrderField[] { Article.ARTICLE.ID }, true);
        public static Index ATTACHMENT_ATTACHMENT_COMMENT_ID_FK = createIndex("attachment_comment_id_fk", Attachment.ATTACHMENT, new OrderField[] { Attachment.ATTACHMENT.OWNBY }, false);
        public static Index ATTACHMENT_PRIMARY = createIndex("PRIMARY", Attachment.ATTACHMENT, new OrderField[] { Attachment.ATTACHMENT.ID }, true);
        public static Index COMMENT_COMMENT_ARTICLE_ID_FK = createIndex("comment_article_id_fk", Comment.COMMENT, new OrderField[] { Comment.COMMENT.PARENT_ARTICLE }, false);
        public static Index COMMENT_COMMENT_COMMENT_ID_FK = createIndex("comment_comment_id_fk", Comment.COMMENT, new OrderField[] { Comment.COMMENT.PARENT_COMMENT }, false);
        public static Index COMMENT_COMMENT_USER_ID_FK = createIndex("comment_user_id_fk", Comment.COMMENT, new OrderField[] { Comment.COMMENT.COMMENTER }, false);
        public static Index COMMENT_PRIMARY = createIndex("PRIMARY", Comment.COMMENT, new OrderField[] { Comment.COMMENT.ID }, true);
        public static Index FOLLOW_RELATION_FOLLOW_RELATION_FOLLOWED_ID_FK = createIndex("follow_relation_followed_id_fk", FollowRelation.FOLLOW_RELATION, new OrderField[] { FollowRelation.FOLLOW_RELATION.FOLLOWEE }, false);
        public static Index FOLLOW_RELATION_FOLLOW_RELATION_FOLLOWING_ID_FK = createIndex("follow_relation_following_id_fk", FollowRelation.FOLLOW_RELATION, new OrderField[] { FollowRelation.FOLLOW_RELATION.FOLLOWER }, false);
        public static Index FOLLOW_RELATION_PRIMARY = createIndex("PRIMARY", FollowRelation.FOLLOW_RELATION, new OrderField[] { FollowRelation.FOLLOW_RELATION.ID }, true);
        public static Index USER_PRIMARY = createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index USER_USER_EMAIL_UINDEX = createIndex("user_email_uindex", User.USER, new OrderField[] { User.USER.EMAIL }, true);
        public static Index USER_USER_USER_NAME_UINDEX = createIndex("user_user_name_uindex", User.USER, new OrderField[] { User.USER.USER_NAME }, true);
    }
}
