/*
 * This file is generated by jOOQ.
*/
package ORM;


import ORM.tables.Article;
import ORM.tables.Attachment;
import ORM.tables.Comment;
import ORM.tables.FollowRelation;
import ORM.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MallardDev extends SchemaImpl {

    private static final long serialVersionUID = 992575276;

    /**
     * The reference instance of <code>mallard_dev</code>
     */
    public static final MallardDev MALLARD_DEV = new MallardDev();

    /**
     * The table <code>mallard_dev.article</code>.
     */
    public final Article ARTICLE = ORM.tables.Article.ARTICLE;

    /**
     * The table <code>mallard_dev.attachment</code>.
     */
    public final Attachment ATTACHMENT = ORM.tables.Attachment.ATTACHMENT;

    /**
     * The table <code>mallard_dev.comment</code>.
     */
    public final Comment COMMENT = ORM.tables.Comment.COMMENT;

    /**
     * The table <code>mallard_dev.follow_relation</code>.
     */
    public final FollowRelation FOLLOW_RELATION = ORM.tables.FollowRelation.FOLLOW_RELATION;

    /**
     * The table <code>mallard_dev.user</code>.
     */
    public final User USER = ORM.tables.User.USER;

    /**
     * No further instances allowed
     */
    private MallardDev() {
        super("mallard_dev", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Article.ARTICLE,
            Attachment.ATTACHMENT,
            Comment.COMMENT,
            FollowRelation.FOLLOW_RELATION,
            User.USER);
    }
}
