/*
 * This file is generated by jOOQ.
*/
package ORM;


import ORM.tables.Article;
import ORM.tables.Attachment;
import ORM.tables.Comment;
import ORM.tables.FollowRelation;
import ORM.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mallard_dev
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mallard_dev.article</code>.
     */
    public static final Article ARTICLE = ORM.tables.Article.ARTICLE;

    /**
     * The table <code>mallard_dev.attachment</code>.
     */
    public static final Attachment ATTACHMENT = ORM.tables.Attachment.ATTACHMENT;

    /**
     * The table <code>mallard_dev.comment</code>.
     */
    public static final Comment COMMENT = ORM.tables.Comment.COMMENT;

    /**
     * The table <code>mallard_dev.follow_relation</code>.
     */
    public static final FollowRelation FOLLOW_RELATION = ORM.tables.FollowRelation.FOLLOW_RELATION;

    /**
     * The table <code>mallard_dev.user</code>.
     */
    public static final User USER = ORM.tables.User.USER;
}
