/*
 * This file is generated by jOOQ.
*/
package ORM.tables.records;


import ORM.tables.Article;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleRecord extends UpdatableRecordImpl<ArticleRecord> implements Record9<Integer, String, Integer, Integer, Integer, Timestamp, Timestamp, Timestamp, Byte> {

    private static final long serialVersionUID = 375414919;

    /**
     * Setter for <code>mallard_dev.article.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mallard_dev.article.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mallard_dev.article.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mallard_dev.article.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mallard_dev.article.author</code>.
     */
    public void setAuthor(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mallard_dev.article.author</code>.
     */
    public Integer getAuthor() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mallard_dev.article.like_num</code>.
     */
    public void setLikeNum(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>mallard_dev.article.like_num</code>.
     */
    public Integer getLikeNum() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>mallard_dev.article.abuse_num</code>.
     */
    public void setAbuseNum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>mallard_dev.article.abuse_num</code>.
     */
    public Integer getAbuseNum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>mallard_dev.article.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>mallard_dev.article.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>mallard_dev.article.edit_time</code>.
     */
    public void setEditTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>mallard_dev.article.edit_time</code>.
     */
    public Timestamp getEditTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>mallard_dev.article.valid_time</code>.
     */
    public void setValidTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>mallard_dev.article.valid_time</code>.
     */
    public Timestamp getValidTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>mallard_dev.article.show_hide_status</code>.
     */
    public void setShowHideStatus(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>mallard_dev.article.show_hide_status</code>.
     */
    public Byte getShowHideStatus() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, Integer, Integer, Timestamp, Timestamp, Timestamp, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, Integer, Integer, Timestamp, Timestamp, Timestamp, Byte> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Article.ARTICLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Article.ARTICLE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Article.ARTICLE.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Article.ARTICLE.LIKE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Article.ARTICLE.ABUSE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Article.ARTICLE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Article.ARTICLE.EDIT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Article.ARTICLE.VALID_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return Article.ARTICLE.SHOW_HIDE_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getLikeNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getAbuseNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getEditTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getValidTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getShowHideStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getLikeNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getAbuseNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getEditTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getValidTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getShowHideStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value2(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value3(Integer value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value4(Integer value) {
        setLikeNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value5(Integer value) {
        setAbuseNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value7(Timestamp value) {
        setEditTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value8(Timestamp value) {
        setValidTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value9(Byte value) {
        setShowHideStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, Timestamp value6, Timestamp value7, Timestamp value8, Byte value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleRecord
     */
    public ArticleRecord() {
        super(Article.ARTICLE);
    }

    /**
     * Create a detached, initialised ArticleRecord
     */
    public ArticleRecord(Integer id, String content, Integer author, Integer likeNum, Integer abuseNum, Timestamp createTime, Timestamp editTime, Timestamp validTime, Byte showHideStatus) {
        super(Article.ARTICLE);

        set(0, id);
        set(1, content);
        set(2, author);
        set(3, likeNum);
        set(4, abuseNum);
        set(5, createTime);
        set(6, editTime);
        set(7, validTime);
        set(8, showHideStatus);
    }
}
