/*
 * This file is generated by jOOQ.
*/
package ORM.tables.records;


import ORM.tables.Comment;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentRecord extends UpdatableRecordImpl<CommentRecord> implements Record9<Integer, String, Integer, Timestamp, Timestamp, Integer, Integer, Integer, Byte> {

    private static final long serialVersionUID = 823176590;

    /**
     * Setter for <code>mallard_dev.comment.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mallard_dev.comment.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mallard_dev.comment.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mallard_dev.comment.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mallard_dev.comment.commenter</code>.
     */
    public void setCommenter(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mallard_dev.comment.commenter</code>.
     */
    public Integer getCommenter() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mallard_dev.comment.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>mallard_dev.comment.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>mallard_dev.comment.edit_time</code>.
     */
    public void setEditTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>mallard_dev.comment.edit_time</code>.
     */
    public Timestamp getEditTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>mallard_dev.comment.abuse_num</code>.
     */
    public void setAbuseNum(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>mallard_dev.comment.abuse_num</code>.
     */
    public Integer getAbuseNum() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>mallard_dev.comment.parent_article</code>.
     */
    public void setParentArticle(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>mallard_dev.comment.parent_article</code>.
     */
    public Integer getParentArticle() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>mallard_dev.comment.parent_comment</code>.
     */
    public void setParentComment(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>mallard_dev.comment.parent_comment</code>.
     */
    public Integer getParentComment() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>mallard_dev.comment.show_hide_status</code>.
     */
    public void setShowHideStatus(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>mallard_dev.comment.show_hide_status</code>.
     */
    public Byte getShowHideStatus() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, Timestamp, Timestamp, Integer, Integer, Integer, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, Timestamp, Timestamp, Integer, Integer, Integer, Byte> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Comment.COMMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Comment.COMMENT.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Comment.COMMENT.COMMENTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Comment.COMMENT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Comment.COMMENT.EDIT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Comment.COMMENT.ABUSE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Comment.COMMENT.PARENT_ARTICLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Comment.COMMENT.PARENT_COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return Comment.COMMENT.SHOW_HIDE_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCommenter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getEditTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getAbuseNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getParentArticle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getParentComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getShowHideStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCommenter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getEditTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getAbuseNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getParentArticle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getParentComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getShowHideStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentRecord value2(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentRecord value3(Integer value) {
        setCommenter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentRecord value4(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentRecord value5(Timestamp value) {
        setEditTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentRecord value6(Integer value) {
        setAbuseNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentRecord value7(Integer value) {
        setParentArticle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentRecord value8(Integer value) {
        setParentComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentRecord value9(Byte value) {
        setShowHideStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommentRecord values(Integer value1, String value2, Integer value3, Timestamp value4, Timestamp value5, Integer value6, Integer value7, Integer value8, Byte value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommentRecord
     */
    public CommentRecord() {
        super(Comment.COMMENT);
    }

    /**
     * Create a detached, initialised CommentRecord
     */
    public CommentRecord(Integer id, String content, Integer commenter, Timestamp createTime, Timestamp editTime, Integer abuseNum, Integer parentArticle, Integer parentComment, Byte showHideStatus) {
        super(Comment.COMMENT);

        set(0, id);
        set(1, content);
        set(2, commenter);
        set(3, createTime);
        set(4, editTime);
        set(5, abuseNum);
        set(6, parentArticle);
        set(7, parentComment);
        set(8, showHideStatus);
    }
}
