/*
 * This file is generated by jOOQ.
*/
package ORM.tables.records;


import ORM.tables.FollowRelation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FollowRelationRecord extends UpdatableRecordImpl<FollowRelationRecord> implements Record4<Integer, Integer, Integer, Byte> {

    private static final long serialVersionUID = -1766669913;

    /**
     * Setter for <code>mallard_dev.follow_relation.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mallard_dev.follow_relation.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mallard_dev.follow_relation.followee</code>.
     */
    public void setFollowee(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mallard_dev.follow_relation.followee</code>.
     */
    public Integer getFollowee() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mallard_dev.follow_relation.follower</code>.
     */
    public void setFollower(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mallard_dev.follow_relation.follower</code>.
     */
    public Integer getFollower() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mallard_dev.follow_relation.isValid</code>.
     */
    public void setIsvalid(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>mallard_dev.follow_relation.isValid</code>.
     */
    public Byte getIsvalid() {
        return (Byte) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Byte> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Byte> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return FollowRelation.FOLLOW_RELATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return FollowRelation.FOLLOW_RELATION.FOLLOWEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return FollowRelation.FOLLOW_RELATION.FOLLOWER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return FollowRelation.FOLLOW_RELATION.ISVALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFollowee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getFollower();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getIsvalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFollowee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFollower();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getIsvalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowRelationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowRelationRecord value2(Integer value) {
        setFollowee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowRelationRecord value3(Integer value) {
        setFollower(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowRelationRecord value4(Byte value) {
        setIsvalid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FollowRelationRecord values(Integer value1, Integer value2, Integer value3, Byte value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FollowRelationRecord
     */
    public FollowRelationRecord() {
        super(FollowRelation.FOLLOW_RELATION);
    }

    /**
     * Create a detached, initialised FollowRelationRecord
     */
    public FollowRelationRecord(Integer id, Integer followee, Integer follower, Byte isvalid) {
        super(FollowRelation.FOLLOW_RELATION);

        set(0, id);
        set(1, followee);
        set(2, follower);
        set(3, isvalid);
    }
}
