/*
 * This file is generated by jOOQ.
*/
package ORM.tables.records;


import ORM.tables.User;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record16<Integer, String, String, String, String, String, Integer, Date, Integer, Timestamp, String, String, String, String, String, Byte> {

    private static final long serialVersionUID = 1331287853;

    /**
     * Setter for <code>mallard_dev.user.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mallard_dev.user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mallard_dev.user.user_name</code>.
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mallard_dev.user.user_name</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mallard_dev.user.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mallard_dev.user.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mallard_dev.user.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mallard_dev.user.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mallard_dev.user.f_name</code>.
     */
    public void setFName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mallard_dev.user.f_name</code>.
     */
    public String getFName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mallard_dev.user.l_name</code>.
     */
    public void setLName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mallard_dev.user.l_name</code>.
     */
    public String getLName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mallard_dev.user.gender</code>.
     */
    public void setGender(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>mallard_dev.user.gender</code>.
     */
    public Integer getGender() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>mallard_dev.user.dob</code>.
     */
    public void setDob(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>mallard_dev.user.dob</code>.
     */
    public Date getDob() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>mallard_dev.user.system_role</code>.
     */
    public void setSystemRole(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>mallard_dev.user.system_role</code>.
     */
    public Integer getSystemRole() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>mallard_dev.user.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>mallard_dev.user.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>mallard_dev.user.country</code>.
     */
    public void setCountry(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mallard_dev.user.country</code>.
     */
    public String getCountry() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mallard_dev.user.state</code>.
     */
    public void setState(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mallard_dev.user.state</code>.
     */
    public String getState() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mallard_dev.user.city</code>.
     */
    public void setCity(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>mallard_dev.user.city</code>.
     */
    public String getCity() {
        return (String) get(12);
    }

    /**
     * Setter for <code>mallard_dev.user.address</code>.
     */
    public void setAddress(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>mallard_dev.user.address</code>.
     */
    public String getAddress() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mallard_dev.user.description</code>.
     */
    public void setDescription(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>mallard_dev.user.description</code>.
     */
    public String getDescription() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mallard_dev.user.isValid</code>.
     */
    public void setIsvalid(Byte value) {
        set(15, value);
    }

    /**
     * Getter for <code>mallard_dev.user.isValid</code>.
     */
    public Byte getIsvalid() {
        return (Byte) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, String, String, String, String, Integer, Date, Integer, Timestamp, String, String, String, String, String, Byte> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, String, String, String, String, Integer, Date, Integer, Timestamp, String, String, String, String, String, Byte> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return User.USER.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return User.USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return User.USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return User.USER.F_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return User.USER.L_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return User.USER.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return User.USER.DOB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return User.USER.SYSTEM_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return User.USER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return User.USER.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return User.USER.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return User.USER.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return User.USER.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return User.USER.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field16() {
        return User.USER.ISVALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getFName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component8() {
        return getDob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getSystemRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component16() {
        return getIsvalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getDob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getSystemRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value16() {
        return getIsvalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value5(String value) {
        setFName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value6(String value) {
        setLName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value7(Integer value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value8(Date value) {
        setDob(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value9(Integer value) {
        setSystemRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value10(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value11(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value12(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value13(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value14(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value15(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value16(Byte value) {
        setIsvalid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Integer value7, Date value8, Integer value9, Timestamp value10, String value11, String value12, String value13, String value14, String value15, Byte value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String userName, String password, String email, String fName, String lName, Integer gender, Date dob, Integer systemRole, Timestamp createTime, String country, String state, String city, String address, String description, Byte isvalid) {
        super(User.USER);

        set(0, id);
        set(1, userName);
        set(2, password);
        set(3, email);
        set(4, fName);
        set(5, lName);
        set(6, gender);
        set(7, dob);
        set(8, systemRole);
        set(9, createTime);
        set(10, country);
        set(11, state);
        set(12, city);
        set(13, address);
        set(14, description);
        set(15, isvalid);
    }
}
