/*
 * This file is generated by jOOQ.
*/
package ORM_jooq;


import ORM_jooq.tables.UserInfo;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>mallard_dev</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USER_INFO_PRIMARY = Indexes0.USER_INFO_PRIMARY;
    public static final Index USER_INFO_USER_INFO_USERNAME_UINDEX = Indexes0.USER_INFO_USER_INFO_USERNAME_UINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index USER_INFO_PRIMARY = createIndex("PRIMARY", UserInfo.USER_INFO, new OrderField[] { UserInfo.USER_INFO.ID }, true);
        public static Index USER_INFO_USER_INFO_USERNAME_UINDEX = createIndex("user_info_username_uindex", UserInfo.USER_INFO, new OrderField[] { UserInfo.USER_INFO.USERNAME }, true);
    }
}
