/*
 * This file is generated by jOOQ.
*/
package ORM_jooq;


import ORM_jooq.tables.UserInfo;
import ORM_jooq.tables.records.UserInfoRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>mallard_dev</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<UserInfoRecord, Integer> IDENTITY_USER_INFO = Identities0.IDENTITY_USER_INFO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserInfoRecord> KEY_USER_INFO_PRIMARY = UniqueKeys0.KEY_USER_INFO_PRIMARY;
    public static final UniqueKey<UserInfoRecord> KEY_USER_INFO_USER_INFO_USERNAME_UINDEX = UniqueKeys0.KEY_USER_INFO_USER_INFO_USERNAME_UINDEX;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<UserInfoRecord, Integer> IDENTITY_USER_INFO = createIdentity(UserInfo.USER_INFO, UserInfo.USER_INFO.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<UserInfoRecord> KEY_USER_INFO_PRIMARY = createUniqueKey(UserInfo.USER_INFO, "KEY_user_info_PRIMARY", UserInfo.USER_INFO.ID);
        public static final UniqueKey<UserInfoRecord> KEY_USER_INFO_USER_INFO_USERNAME_UINDEX = createUniqueKey(UserInfo.USER_INFO, "KEY_user_info_user_info_username_uindex", UserInfo.USER_INFO.USERNAME);
    }
}
