/*
 * This file is generated by jOOQ.
*/
package ORM_jooq;


import ORM_jooq.tables.UserInfo;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MallardDev extends SchemaImpl {

    private static final long serialVersionUID = -1852077208;

    /**
     * The reference instance of <code>mallard_dev</code>
     */
    public static final MallardDev MALLARD_DEV = new MallardDev();

    /**
     * The table <code>mallard_dev.user_info</code>.
     */
    public final UserInfo USER_INFO = ORM_jooq.tables.UserInfo.USER_INFO;

    /**
     * No further instances allowed
     */
    private MallardDev() {
        super("mallard_dev", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            UserInfo.USER_INFO);
    }
}
