/*
 * This file is generated by jOOQ.
*/
package ORM_jooq;


import ORM_jooq.tables.UserInfo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in mallard_dev
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mallard_dev.user_info</code>.
     */
    public static final UserInfo USER_INFO = ORM_jooq.tables.UserInfo.USER_INFO;
}
